platform: linux
image_resource:
  type: docker-image

inputs:
  - name: gpdb_src
  - name: ccp_src
  - name: cluster_env_files
  - name: plcontainer_src
outputs:

params:
  MAKE_TEST_COMMAND: ""
  BLDWRAP_POSTGRES_CONF_ADDONS: ""
  TEST_OS: ""
  CONFIGURE_FLAGS: ""

run:
  path: plcontainer_src/concourse/scripts/ic_gpdb_resgroup.bash
