platform: linux
image_resource:
  type: docker-image
inputs:
  - name: gpdb_src
  - name: plcontainer_src
  - name: gpdb_binary
  - name: ccp_src
  - name: plcontainer_gpdb_build
  - name: plcontainer_pyclient_docker_image
  - name: plcontainer_rclient_docker_image
  - name: cluster_env_files
  
params:
  platform:
run:
  path: plcontainer_src/concourse/scripts/plcontainer_resgroup_tests.sh
